### ISSUE TITLE
Machine Learning

### ISSUE THREAD

**Issue by rcbxd** [rcbxd/emotext-server#4]
# Idea

To create an API that would analyze the mood of people by their messages

# Data management

We are going to pull the messages data from the JS API and analyze the mood using that data.
The processed data will be served using our Flask API and later sent to the app on requests 

# Algorithm

As of right now we are going to use a supervised learning model for the data, which will consist of a few categories of emotions. The algorithm will run in the following steps.
- [x] Access the data through the APIs.
- [x] Create a DataFrame
- [x] Clean up the data(eg. remove null values)
- [x] Create a table of all the words in the texts and their frequencies.
- [x] Compare the highest frequency words with a dictionary including the general words with the kind of sentiment
- [x] Calculate the percentage of the words of each sentiment
- [x] Return the sentiment with the highest percentage

This algorithm is not as good right now, but I will keep changing it as I learn more

**Comment by devr0306** [comment]
Yeah so that's what the AI is going to do. It's just going to take in the input and form a prediction, and will finally just send the prediction which will be outputted through the JS APIS.

**Comment by rcbxd** [comment]
> Yeah so that's what the AI is going to do. It's just going to take in the input and form a prediction, and will finally just send the prediction which will be outputted through the JS APIS.

Yeah, but I'd like to add much more functionality in the future.

Here are some things I could think of that our app could do:

- Detailed user statistics: show the average response time, their overall traits (how friendly they are, how likely they are to respond within 5 minutes or what subjects you should not discuss with them) 
- Allow users to hide your statistics in the settings
- Give some advice on how to chat with certain people
- Show your communication progress

This could really change the marketing situation for us, and also better the user experience by showing the ads when using those exclusive features or by making users pay for them.

Of course, right now we can't do most of that, because we are a really small team and we would either need a lot of time or more people. Right now we should focus on the Beta version of Client+Server with some AI functionality and then think about the features

**Comment by rcbxd** [comment]
APIs are finally done. Now we can detect the mood using Flask APIs. Some model training is still needed.
